name: 🕒 Update Age in README
permissions:
  contents: write

on:
  schedule:
    - cron: "0 0 1 * *"   # Runs monthly on the 1st
  workflow_dispatch:       # Allows manual trigger too

jobs:
  update-age:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Run age update script
        run: python .github/scripts/update_age.py

      - name: Commit and push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "🕒 Auto-update age" || echo "No changes"
          git push
